apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      hostIPC: true
      hostPID: true
      hostNetwork: true
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
        fsGroupChangePolicy: Always
      containers:
      - name: django-app
        image: <Registry>/django-app:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        securityContext:
          runAsUser: 2000
          runAsNonRoot: false
          allowPrivilegeEscalation: true
          readOnlyRootFilesystem: false
          privileged: true
          capabilities:
            add: ["NET_ADMIN", "SYS_TIME"]
---
apiVersion: v1
kind: Service
metadata:
  name: django-app
spec:
  selector:
    app: django-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000   
  type: NodePort